name: Update VERSION

on:
  push:
    branches: [master]
    paths-ignore:
      - VERSION

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ github.sha }}" > VERSION
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update VERSION [skip ci]"
          file_pattern: VERSION
